
env:
  PORT: 80

replicaCount: 1

image:
  repository: gcr.io/env-flowai/github-flow-ai-duckling
  tag: bf6cb1b33500c32c97f7306ca7c3ed4f491bb407 
  pullPolicy: Always

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: "app"
    nginx.ingress.kubernetes.io/ssl-redirect: false
    nginx.ingress.kubernetes.io/rewrite-target: "/"
  path: /duckling
  host: app-dev.flow.ai
#  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local